# Generated by Django 3.1.5 on 2021-01-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='主机名称')),
                ('ip_addr', models.CharField(max_length=32, verbose_name='主机地址')),
            ],
            options={
                'verbose_name': '主机表',
                'verbose_name_plural': '主机表',
            },
        ),
    ]
